language: php

branches:
#  only:
#    - master
#    - develop

compiler:
    - gcc
    - clang

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    
script: /usr/bin/env sh ./build-scripts/travis.sh

after_failure:
    - echo "${PSXRT_MAKE_TEST}"