language: php

branches:
#  only:
#    - master
#    - develop

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    
script: source ./build-scripts/travis/main.sh

after_failure:
    - source ./build-scripts/travis/after_failure.sh